---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Зарегистрированный пользователь должен иметь возможность войти в систему
  - Пользователь может менять язык программирования для удобства прохождения игры
  - Пользователь может менять локаль для удобства восприятия информации
  - Пользователь может корректировать игру под себя выбрать уровень сложности
    тип игры
  - Пользователь может пригласить друга для совместной игры
  - Зарегистрированные пользователи могут общаться в общем чате с другими пользователями
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
implicit:
  - Пользовательский интерфейс должен быть интуитивно понятным, чтобы новые
    пользователи могли легко начать работу без необходимости в обширных
    инструкциях
  - Элементы управления должны быть логично сгруппированы, чтобы пользователи
    могли быстро находить необходимые функции
  - Дизайн сайта должен быть современным и соответствовать актуальным
    веб-тенденциям
  - Поддержка пользователей должна быть доступна 24/7 через различные каналы
    (чат, электронная почта, форумы)
  - Сайт должен быть локализован для поддержки различных языков и культур, чтобы
    сделать его доступным для пользователей из разных стран